### ISSUE TITLE
사용자 인증 & 정보 입력_UI 작업

### ISSUE THREAD

**Issue by HyeonJunSong** [team-cret/during-client#7]
### Description
사용자 인증 및 정보 입력 UI 작업

### ToDo
- [x] Oauth 페이지
- [x] 약관 페이지
- [x] 이름 입력 페이지
- [x] 생년월일 입력 페이지
- [x] 연인 초대 페이지
